version: '3'
services:
  docs:
    image: squidfunk/mkdocs-material
    ports:
      - "8000:8000"
    volumes:
      - .:/docs
  docs-build:
    image: squidfunk/mkdocs-material
    volumes:
      - .:/docs
    command: build