site_name: Minecraft Slack Integration Plugin wiki

repo_url: https://github.com/howyi/MCSlackIntegration
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Installation:
      - install_to_server.md
      - slack_app.md
  - Update: update_plugin.md
  - Configs: config.md

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
  features:
    - navigation.expand
    - content.action.edit
    - content.code.copy
  palette:
    primary: black
    scheme: default

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables