# https://api.slack.com/tutorials/tracks/getting-a-token
# REQUIRED PERMISSIONS:
#  channels:history
#  users:read
#  channels:write.topic
#  chat:write
#  chat:write.customize
SlackToken: "xoxb-xxxxxxxxxxxxx-xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxx"
# Slack to minecraft
# Socket Mode Token
# REQUIRED PERMISSIONS:
#  connections:write
# Event Subscriptions: true
SlackSocketToken: "xapp-xxxxxxxxxxxxx-xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxx"
SlackBotName: "SlackChannelSRV"
SlackBotIconEmoji: ":pick:"
SlackBotIconUrl: ""

# https://help.socialintents.com/article/148-how-to-find-your-slack-team-id-and-slack-channel-id
# *Bot must be invited to the channel to be notified*
SlackChannelId: "C05NP1XXXXX"

Message:
  # If message is set to an empty string, no notification will be sent.
  ServerStart: "server start"
  ServerEnd: "server end"
  # ex.{0}: hoyash
  PlayerJoin: "{0} joined the game"
  # ex.{0}: hoyash
  PlayerQuit: "{0} left the game"
  # ex.{0}: hoyash was shot by Skeleton
  PlayerDeath: "{0}"
  # ex.{0}: hello
  PlayerChat: "{0}"
  # ex.{0}: hoyash
  PlayerChatName: "{0}"
  # ex.{0}: t-hayashi
  # ex.{1}: hello from slack
  FromSlackChat: "#[{0}] {1}"

StatusChannelTopic:
  Enabled: false
  Online: "🟢 online: {0}"
  Offline: "🔴 offline"