Version: 1

# slack app parameters
# read the plugin document: https://howyi.github.io/SlackIntegration/
SlackToken: ""
SlackSocketToken: ""

# Username settings for posting info messages to slack
# If IconUrl is set, it will be used in preference to IconEmoji
SlackBotName: "Minecraft server"
SlackBotIconEmoji: ":pick:"
SlackBotIconUrl: "https://howyi.github.io/MCSlackIntegration/images/minecraft_icon.png"


Message:
  # slack post message on server start
  # ※Do not post if empty
  ServerStart: "server start"
  # slack post message on server end
  # ※Do not post if empty
  ServerEnd: "server end"
  # slack post message on player join
  # ※Do not post if empty
  # {0}: joined player name
  # ex. hoyash
  PlayerJoin: "{0} joined the game"
  # slack post message on player leave
  # ※Do not post if empty
  # {0}: left player name
  # ex. hoyash
  PlayerQuit: "{0} left the game"
  # slack post message on player dead
  # ※Do not post if empty
  # {0}: death message
  # ex. hoyash was shot by Skeleton
  PlayerDeath: "{0}"
  # slack post message on player chat
  # ※Do not post if empty
  # {0}: minecraft player chat text
  # ec: hello
  PlayerChat: "{0}"
  # slack post username on player chat
  # {0}: minecraft player name
  # ec: hello
  PlayerChatName: "{0}"
  # Format for chatting posts on connected slack channels to minecraft
  # ※Do not post if empty
  # {0}: Slack username
  # ex. t-hayashi
  # {1}: Slack post text
  # ex: hello from slack
  FromSlackChat: "#[{0}] {1}"

ConsoleChannel:
  Executable: True
  ExecutableSlackUserNames: ""
  SlackChannelId: ""

# Display the online status of the server on the linked channel's topic
StatusChannelTopic:
  Enabled: false
  # Topic text during server online
  # {0}: Online Player count
  # ex. 1
  Online: "🟢 online: {0}"
  # Topic text during server offline
  Offline: "🔴 offline"

# Information to be displayed in Slack's App Home
AppHome:
  # online player count
  # {0}: online player count
  # ex. 1
  # {1}: max player count
  # ex. 20
  OnlineUserCount: "online: {0}/{1}"
  # online player list
  OnlineUserList: true